### ISSUE TITLE
hddtemp displays same value as during startup

### ISSUE THREAD

**Issue by martivo** [ncabatoff/sensor-exporter#4]
Hi, 
there seems to be a bug with hddtemp fetching. I am not sure if it is a retry issue or something else. But seems the temperatures get stuck on the position they were when sensor-exporter starts.

I have hddtemp running on my host machine and sensor-exporter in docker. 
```
[root@loovsys ~]# docker logs sensors
2018/11/19 15:45:24 error readding hddtemps: error connecting to hddtemp address '192.168.0.2:7634': dial tcp 192.168.0.2:7634: getsockopt: connection refused
[root@loovsys ~]# docker exec -it 31c4388720e8 bash
root@31c4388720e8:/go# curl 192.168.0.2:7634

curl: (56) Recv failure: Connection reset by peer
|/dev/sda|Samsung SSD 840 EVO 500GB|45|C||/dev/sdb|WDC WD40PURX-64GVNY0|42|C||/dev/sdc|WDC WD40EZRZ-00GXCB0|41|C|root@31c4388720e8:/go# 
root@31c4388720e8:/go# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Nov19 ?        00:00:00 /bin/sh -c /go/bin/sensor-exporter -hddtemp-address=192.168.0.2:7634
root         8     1  0 Nov19 ?        00:00:17 /go/bin/sensor-exporter -hddtemp-address=192.168.0.2:7634
root        23     0  0 11:02 pts/0    00:00:00 bash
root        31    23  0 11:07 pts/0    00:00:00 ps -ef

```
It has one line about failed to fetch. From grafana the only change in temperature happend when I restarted sensors-exporter.

![screenshot_20181120_130355](https://user-images.githubusercontent.com/29144235/48769618-c8b74800-ecc4-11e8-9fc3-d4e711916795.png)

From screenshot you can see that it should show different temperatures.

For example hda temperature is 45C, but sesnors-exporter reports it as 38 (as it was when sensor-exporter started up)

**Comment by martivo** [comment]
Hi, so I had time to debug this. The issue is that the connection is not done again...so the same connection buffer is used every time.

By re-initializing h.Init() and closing connection every time readTempsFromConn is called. Also needed to wipe the h.buf to insert the returned values from new connection.

```
diff --git a/sensor-exporter/main.go b/sensor-exporter/main.go
index 1641ec1..986fa39 100644
--- a/sensor-exporter/main.go
+++ b/sensor-exporter/main.go
@@ -161,16 +161,17 @@ func (h *HddCollector) Init() error {
 }
 
 func (h *HddCollector) readTempsFromConn() (string, error) {
-       if h.conn == nil {
+       //if h.conn == nil {
                if err := h.Init(); err != nil {
                        return "", err
                }
-       }
-
+       //}
+        h.buf.Reset()
        _, err := io.Copy(&h.buf, h.conn)
        if err != nil {
                return "", fmt.Errorf("Error reading from hddtemp socket: %v", err)
        }
+        h.conn.Close()
        return h.buf.String(), nil
 }
```


The function in main.go now looks like this and it works properly:
```
func (h *HddCollector) readTempsFromConn() (string, error) {
        //if h.conn == nil {
                if err := h.Init(); err != nil {
                        return "", err
                }
        //}
        h.buf.Reset()
        _, err := io.Copy(&h.buf, h.conn)
        if err != nil {
                return "", fmt.Errorf("Error reading from hddtemp socket: %v", err)
        }
        h.conn.Close()
        return h.buf.String(), nil
}

```

**Comment by martivo** [comment]
For me this issue is now resolved :-)

**Comment by webvictim** [comment]
@mardicas Please create a pull request with this fix!

**Comment by martivo** [comment]
Be gentle, it is my first pull request on github.

**Comment by martivo** [comment]
Now the HDD graph looks correct , instead of a straight line after startup it actualy changes.
![screenshot_20190212_225022](https://user-images.githubusercontent.com/29144235/52667131-bb52d800-2f18-11e9-95f9-b3565f38a07a.png)
